# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/service/bulb_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esrc/service/bulb_service.proto\x12\x04\x62ulb\"\x07\n\x05\x45mpty\"A\n\x0e\x42ulbProperties\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05power\x18\x02 \x01(\t\x12\x12\n\nbrightness\x18\x03 \x01(\t2A\n\x0b\x42ulbService\x12\x32\n\rGetProperties\x12\x0b.bulb.Empty\x1a\x14.bulb.BulbPropertiesb\x06proto3')


_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'src.service.bulb_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals['_EMPTY']._serialized_start = 40
    _globals['_EMPTY']._serialized_end = 47
    _globals['_BULBPROPERTIES']._serialized_start = 49
    _globals['_BULBPROPERTIES']._serialized_end = 114
    _globals['_BULBSERVICE']._serialized_start = 116
    _globals['_BULBSERVICE']._serialized_end = 181
# @@protoc_insertion_point(module_scope)
