# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
sys.path.append('.')
from src.services import bulb_service_pb2 as src_dot_service_dot_bulb__service__pb2


class BulbServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProperties = channel.unary_unary(
                '/bulb.BulbService/GetProperties',
                request_serializer=src_dot_service_dot_bulb__service__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_service_dot_bulb__service__pb2.BulbProperties.FromString,
                )


class BulbServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BulbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperties,
                    request_deserializer=src_dot_service_dot_bulb__service__pb2.Empty.FromString,
                    response_serializer=src_dot_service_dot_bulb__service__pb2.BulbProperties.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bulb.BulbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BulbService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bulb.BulbService/GetProperties',
            src_dot_service_dot_bulb__service__pb2.Empty.SerializeToString,
            src_dot_service_dot_bulb__service__pb2.BulbProperties.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
